### ISSUE TITLE
Choosing a dataset

### ISSUE THREAD

**Issue by GeorgeJJW** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#1]
Found some fun and simple alternatives to the bakery data sets for us to choose from:

https://www.kaggle.com/shrutimehta/zomato-restaurants-data
https://www.kaggle.com/residentmario/ramen-ratings
https://www.kaggle.com/rtatman/chocolate-bar-ratings

I just love working with food data, they are fun! 
Feel free to link us more.

**Comment by blei7** [comment]
The chocolate seem pretty interesting. Let’s pick the chocolate, since there seem to be lots of question we can create base on it.

**Comment by GeorgeJJW** [comment]
Yeah I agree, let's do the chocolate one

**Comment by GeorgeJJW** [comment]
A dataset is chosen.
