### ISSUE TITLE
Milestone1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#19]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] Use propper citation format. 

**Reasoning**
- [x] Briefly explain in your main README.md what each command does.
- [x] In your main README.md file, include a short high-level summary of your report in your main README.md. 
- [x] Seems  like you arbatrarely divided the ratings into low and high ratings. Why did you decide on spliting at 3? Why not in half (2.5)? 
> We observed that chocolate experts tend to give somewhat lower ratings as chocolate became more dark. We also observed that low quality chocolate tends to be more dark than high quality chocolate. 
- [x] ^Too strong of a conclusion. Your correaltion was almost 1.0 (no correaltion) and the mean chocolate darkness (cocoa percentage) between low and high expert raing was only about 1.2%. Is a 1.2% difference meaningful desite being singnificant? It seems that there is no meaninful relationship in cocoa percentage and expert raiting. 
- [x] Great discussion on limitations. Could talk more about future directions. 

**Visualization**
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)" Figure 3 caption is good. 
- [x] Table 1 and 2 have the same caption but different table. Captions should be different. 
- [x] Axis name "Frequency" is not very meaningful. 

**Quality -- Robustness and Maintainability**
- [x] Should have a unit test in each script (because we did not clearly mention this in the instructions, we did not reduct points for not having a unit test)

**Comment by GeorgeJJW** [comment]
Thanks for the in depth feedback! We tried our best to address all your concerns.

Also, here is a list of all the 100% dark chocolate from the original data set :chocolate_bar:. 

![image](https://user-images.githubusercontent.com/3982153/49326106-e759e200-f501-11e8-8415-2087c8e880a2.png)
