### ISSUE TITLE
Peer's Feedback

### ISSUE THREAD

**Issue by blei7** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#20]
Need improvements:
-~~Place report summary before  the chocolate picture.~~
-~~Explain what each script does in more details~~
-Organize the result folder with a table folder and a figure folder
-~~Limitation need to take into account that majority of the data consist of high cocoa concentration at 70% already~~
-Add figure and table labels to the flowchart
-~~Specify the version of the dependencies~~
-~~More explanation on why rating is categorical~~   
-~~Future direction should elaborate on what data set to subset~~

Things we did great:
-Great choice of data set
-Each script takes only one input and save only one output.

**Comment by GeorgeJJW** [comment]
Improvements were made where we deemed applicable.

These improvement suggestions were struck out from the list as we made the changes.
