### ISSUE TITLE
Running Docker and Make on Windows's cmd and powershell

### ISSUE THREAD

**Issue by blei7** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#26]
For user running Windows, the <PATH_ON_YOUR_COMPUTER> must be using "/ " instead of " \ " , also there should be no " : " next to the drive letter.  The " // " must be added to the beginning of the <PATH_ON_YOUR_COMPUTER>.

The general format for running Make **interactively** using Docker in Window's cmd or powershell:

`docker run --rm -it -e PASSWORD=<YOURPASSWORD> -v <PATH_ON_YOUR_COMPUTER>:<DOCKER_CONTAINER_PATH> <REPOSITORY>:<TAG> //bin/bash`

eg. 
```
docker run --rm -it -e PASSWORD=1234 -v //C/Users/blei/Downloads/DSCI_522_blei7_georgejjw_coco:/home/r
studio/mds-coco-analysis mds-coco-analysis:v0.1 //bin/bash
```

The general format for running Make **non-interactively** using Docker in Window's cmd or powershell:

`docker run --rm -v <PATH_ON_YOUR_COMPUTER>:<DOCKER_CONTAINER_PATH> <REPOSITORY>:<TAG> make -C '<DOCKER_CONTAINER_PATH>' <MAKE_ARGUMENT>`

```
docker run --rm -v //C/Users/blei/Downloads/DSCI_522_blei7_georgejjw_coco:/home/DSCI_522_blei7_georgej
jw_coco wuj4979/mds-coco-analysis:latest make -C "/home/DSCI_522_blei7_georgejjw_coco" clean
```

**Comment by GeorgeJJW** [comment]
Great write-up! I'll be sure to include it in the instructions for Windows users.
