### ISSUE TITLE
v0.1 should contain the full proposal

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#7]
v1.0 contains the full proposal while v0.1 on contains an outline of your proposal. v0.1 should contain the full proposal

**Comment by GeorgeJJW** [comment]
Hi Ali, I actually want to discuss this requirement.

In the `proposal` instructions, for the v0.1 release, it simply mentions that we need to set up a basic file and directory structure, but there's no mentioning of fully fleshing out our proposal.

![image](https://user-images.githubusercontent.com/3982153/48917961-7732c880-ee3e-11e8-9b5a-f0697f32f718.png)

I do agree with you that by v1.0 release, we should have the full proposal, as required by the instructions.

![image](https://user-images.githubusercontent.com/3982153/48918319-8ca8f200-ee40-11e8-96ec-e387e28137cc.png)

Tiffany mentioned in slack that as long as we have a stable link to the final state of our repo as of week 1, the difference between `v0.1` and v`1.0` is not paramount.

![image](https://user-images.githubusercontent.com/3982153/48918288-73a04100-ee40-11e8-8302-851ad24696ae.png)

We can also simply just delete the v0.1 release and go with the v1.0 release solely. We are open to suggestions as to how to address this release versions issue. What do you think?

**Comment by blei7** [comment]
Yeah, I agree with George too.

**Comment by GeorgeJJW** [comment]
On second thoughts, I just want to make @aimirza's life easier, I've rebundled the releases, such that:

v0.1 now contains the full proposal, and is a snapshot of the project by the end of week 1.

v1.0 now contains changes we made to the project in response to your feedback to week 1. 

All the old links to these releases should still work.

**Comment by aimirza** [comment]
Thank you :)
