### ISSUE TITLE
Provide snippet in proposal

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#8]
Thank you for providing proof that you can upload the data. Can you provide a snippet of the data in your proposal?

**Comment by GeorgeJJW** [comment]
Thank you for catching that @aimirza! I've updated the proposal to also include a snippet of the data upon executing the script, as seen in https://github.com/UBC-MDS/DSCI_522_blei7_georgejjw_coco/commit/89ca3a709a954347381b9d5ca960d43c35c52282.
