### ISSUE TITLE
How to calculate linear correlation with non-linear variables

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#9]
You want to assess if there is a linear correlation between cocoa percentage and expert ratings of chocolate. Neither variable is linear. How would you calculate the correlation between the two variables? (Tough question)

**Comment by GeorgeJJW** [comment]
### Nature of the variables

You raised a good point about the potential nonlinearity of the two variables in question!

However, I would still like to entertain the idea that we can treat these two variables both as linearly continuous.

For the cocoa percentage variable, although at first glance it does appear to be discrete/categorical, I argue that we can still treat it as a continuous variable. Specifically. the distance between a 79% (0.79) cocoa percentage and 92% (0.92) cocoa percentage is meaningful and the distance is linear (not exponential or logarithmic).

The expert ratings variable also appear to be ordinal/categorical in nature. A closer look at the expert ratings variable reveals that it  actually employs a rating system that is similar to an ordinal [Likert scale](https://en.wikipedia.org/wiki/Likert_scale). For instance, a chocolate bar can be given a 3 point rating, or a 3.75 rating, or a 5 point rating. There is a body of literature that supports the idea that  "ordinal variables with five or more categories can often be used as continuous without any harm to the analysis you plan to use them in." as seen on the article [here](https://www.statisticssolutions.com/can-an-ordinal-likert-scale-be-a-continuous-variable/).

### Linearity of the relationship between the two variables

I would like to also point out that our research question is largely exploratory in nature. To clarify, our research question is: What is the relationship between cocoa percentage (darkness) and expert ratings.

In other words, before actually visualizing the variables and running the analysis, we are not even sure that there's a relationship between the two variables in the first place. 

If we are to determine that there's actually a meaningful relationship between the two variables, I agree with you that we need to be cautious about whether the relationship is linear or non-linear in nature.

I suggest that we can modify our plan of action to the following: 

We compute the Pearson's correlation coefficient between the two variables assuming their relationship is linear. We then also compute the Kendall's Tau correlation coefficient between the two variables, assuming their relationship is nonlinear. We then compare the two correlation coefficients. 

Does this seem like a good approach to address your concerns about linearity?

**Comment by blei7** [comment]
I agree with George's points, and I would like to ask, what do you mean by neither variable is linear? do you mean they are not quantitative?

**Comment by GeorgeJJW** [comment]
I have to admit, in our scenario, perhaps an alternative approach is to further categorize the expert rating variable and convert the levels into "low ratings" and "high ratings". 

Then we can do a simple t-test and compare the mean chocolate darkness (cocoa percentage) between the lowly rated chocolate and the highly rated chocolate.

We can incorporate this approach as well as into our analysis, time permitting, where we first treat expert rating as a continuous variable, then also further categorize expert rating and treat it as a categorical variable. But I really want this project to remain extremely simple in terms of data analysis (hence only calculating a correlation coefficient), so we can focus much of our efforts on project workflow and scripts setup.

Does this sound reasonable to you @aimirza?

**Comment by GeorgeJJW** [comment]
We implemented both approach this week, running a correlation analysis treating expert ratings as a continuous variable, then performing a hypothesis test treating expert ratings as a categorical variable. We hope this will address your concern about the nature of the variables.

**Comment by aimirza** [comment]
The issue with using cocoa percentage is that it is a compositional variable; Thus, it has a "constant sum constraint." Using traditional statistical analysis methods in analyzing compositional data may not be proper and may cause problems. Here is [one paper](https://www.sciencedirect.com/science/article/pii/S1877050913004870) that describes the problem and gives a solution.

**Comment by aimirza** [comment]
> I have to admit, in our scenario, perhaps an alternative approach is to further categorize the expert rating variable and convert the levels into "low ratings" and "high ratings".

This is a good idea. This is a common approach.
